<?php
$majors = array(
	"BME" => "Biomedical Engineering",
	"BIA" => "Business Intelligence and Analytics",
	"BT" => "Business and Technology",
	"CHE" => "Chemical Engineering",
	"CH" => "Chemistry",
	"CE" => "Civil Engineering",
	"CAL" => "College of Arts &amp; Letters",
	"CPE" => "Computer Engineering",
	"CS" => "Computer Science",
	"CM" => "Construction Management",
	"D" => "Dean's Offices",
	"EE" => "Electrical Engineering",
	"EM" => "Engineering Management",
	"ELC" => "English Language and Communication",
	"ES" => "Enterprise Systems",
	"EN" => "Environmental Engineering",
	"EMT" => "Executive Management of Technology",
	"FE" => "Financial Engineering",
	"H" => "Honor Program",
	"HAR" => "Humanities/Art",
	"HHS" => "Humanities/History",
	"HLI" => "Humanities/Literature",
	"HMU" => "Humanities/Music",
	"HPL" => "Humanities/Philosophy",
	"HST" => "Humanities/Science and Technology Studies",
	"HSS" => "Humanities/Social Sciences",
	"MIS" => "Information Systems",
	"IPD" => "Integrated Product Development",
	"E" => "Interdepartmental Engineering",
	"MGT" => "Management",
	"MT" => "Materials Engineering",
	"MA" => "Mathematics",
	"ME" => "Mechanical Engineering",
	"NANO" => "Nanotechnology",
	"NE" => "Naval Engineering",
	"NIS" => "Networked Information Systems",
	"OE" => "Ocean Engineering",
	"PME" => "Pharmaceutical Manufacturing",
	"PE" => "Physical Education",
	"PEP" => "Physics &amp; Engineering Physics",
	"PAE" => "Product Architecture and Engineering",
	"COMM" => "Professional Communications",
	"PRV" => "Provost",
	"QF" => "Quantitative Finance",
	"REG" => "Registrar",
	"SEF" => "Science &amp; Engineering Found. for Edu.",
	"SOC" => "Service Oriented Computing",
	"SSW" => "Software Engineering",
	"SYS" => "Systems Engineering",
	"SES" => "Systems Engineering Security",
	"TG" => "Technogenesis",
	"TM" => "Telecommunications Management",
	"ARD" => "US Army ARDEC"
);

$degrees = array(
	"Master",
	"PhD"
);

$semesters = array(
	"Fall",
	"Spring"
);
